# Define locations for which builds should be created.
# Builds will be subsampled according to their geographic specificity
# based on the subsampling definitions below.
locations:
  region:
    - global
    - africa
    - asia
    - europe
    - north-america
    - oceania
    - south-america
